# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: main
  pull_request:
    branches: main

defaults:
  run:
   working-directory: ./api
  
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository
      
    steps:
      - name: Clone eepository
        uses: actions/checkout@v4
       
      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install step
        run: "npm install --omit=dev"
        
      - name: Build Step
        run: npm run start
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          API_KEY: ${{secrets.API_KEY}}
          
