# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy

on:
  push:
    branches: main
  pull_request:
    branches: main

defaults:
  run:
   working-directory: ./api
  
   
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository
      
    steps:
    - name: Clone repository
      uses: actions/checkout@v4 

    - name: Install Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
        
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
          
    - name: install step
      run: npm i --omit=dev
      
    - run: |
        touch .env 
        echo "${{ secrets.PROD_ENV_FILE }}" > .env

    - name: Upload to Deno Deploy
      uses: denoland/deployctl@v1
      with:
          project: "joaquinramr-tester-app-40"
          entrypoint: "api/index"
          root: "./api"
          
